charpool.o: charpool.cc nbase/nbase.h nbase/nbase_config.h \
  nbase/nbase_ipv6.h charpool.h nmap_error.h nmap_config.h
FingerPrintResults.o: FingerPrintResults.cc FingerPrintResults.h \
  FPEngine.h nsock/include/nsock.h nsock/include/nsock_config.h \
  libnetutil/npacket.h libnetutil/ApplicationLayerElement.h \
  libnetutil/PacketElement.h nbase/nbase.h nbase/nbase_config.h \
  nbase/nbase_ipv6.h libnetutil/netutil.h libpcap/pcap.h \
  libpcap/pcap/pcap.h libpcap/pcap/bpf.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h osscan.h NmapOps.h nmap.h nmap_config.h \
  scan_lists.h output.h nse_main.h liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lualib.h
FPEngine.o: FPEngine.cc FPEngine.h nsock/include/nsock.h \
  nsock/include/nsock_config.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  nbase/nbase.h nbase/nbase_config.h nbase/nbase_ipv6.h \
  libnetutil/netutil.h libpcap/pcap.h libpcap/pcap/pcap.h \
  libpcap/pcap/bpf.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h Target.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lualib.h scan_lists.h \
  portreasons.h portlist.h scan_engine.h timing.h osscan.h osscan2.h \
  FingerPrintResults.h NmapOps.h nmap.h nmap_config.h output.h \
  nmap_error.h liblinear/linear.h FPModel.h tcpip.h
FPModel.o: FPModel.cc FingerPrintResults.h FPEngine.h \
  nsock/include/nsock.h nsock/include/nsock_config.h \
  libnetutil/npacket.h libnetutil/ApplicationLayerElement.h \
  libnetutil/PacketElement.h nbase/nbase.h nbase/nbase_config.h \
  nbase/nbase_ipv6.h libnetutil/netutil.h libpcap/pcap.h \
  libpcap/pcap/pcap.h libpcap/pcap/bpf.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h osscan.h liblinear/linear.h
idle_scan.o: idle_scan.cc libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  nbase/nbase.h nbase/nbase_config.h nbase/nbase_ipv6.h \
  libnetutil/netutil.h libpcap/pcap.h libpcap/pcap/pcap.h \
  libpcap/pcap/bpf.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h idle_scan.h timing.h osscan2.h nmap.h \
  nmap_config.h scan_lists.h NmapOps.h output.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lualib.h \
  nsock/include/nsock.h nsock/include/nsock_config.h services.h Target.h \
  portreasons.h portlist.h scan_engine.h osscan.h nmap_error.h tcpip.h \
  struct_ip.h
MACLookup.o: MACLookup.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h MACLookup.h NmapOps.h \
  scan_lists.h output.h nse_main.h liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lualib.h nsock/include/nsock.h \
  nsock/include/nsock_config.h nmap_error.h charpool.h
main.o: main.cc nmap.h nmap_config.h nbase/nbase.h nbase/nbase_config.h \
  nbase/nbase_ipv6.h NmapOps.h scan_lists.h output.h nse_main.h \
  liblua/lua.h liblua/luaconf.h liblua/lauxlib.h liblua/lualib.h \
  nsock/include/nsock.h nsock/include/nsock_config.h utils.h \
  nmap_error.h
nmap.o: nmap.cc nmap.h nmap_config.h nbase/nbase.h nbase/nbase_config.h \
  nbase/nbase_ipv6.h osscan.h scan_engine.h scan_lists.h \
  libdnet-stripped/include/dnet.h libdnet-stripped/include/dnet/os.h \
  libdnet-stripped/include/dnet/eth.h libdnet-stripped/include/dnet/ip.h \
  libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h timing.h libpcap/pcap.h \
  libpcap/pcap/pcap.h libpcap/pcap/bpf.h FPEngine.h \
  nsock/include/nsock.h nsock/include/nsock_config.h \
  libnetutil/npacket.h libnetutil/ApplicationLayerElement.h \
  libnetutil/PacketElement.h libnetutil/netutil.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h idle_scan.h NmapOps.h output.h nse_main.h \
  liblua/lua.h liblua/luaconf.h liblua/lauxlib.h liblua/lualib.h \
  MACLookup.h traceroute.h nmap_tty.h nmap_ftp.h services.h targets.h \
  TargetGroup.h tcpip.h NewTargets.h Target.h portreasons.h portlist.h \
  osscan2.h service_scan.h charpool.h nmap_error.h utils.h xml.h \
  libdnet-stripped/include/config.h
nmap_dns.o: nmap_dns.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h NmapOps.h scan_lists.h \
  output.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h nsock/include/nsock.h nsock/include/nsock_config.h \
  nmap_dns.h nmap_error.h nmap_tty.h tcpip.h libpcap/pcap.h \
  libpcap/pcap/pcap.h libpcap/pcap/bpf.h timing.h Target.h \
  libnetutil/netutil.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h portreasons.h portlist.h \
  scan_engine.h osscan.h osscan2.h
nmap_error.o: nmap_error.cc nmap_error.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h output.h scan_lists.h \
  nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h nsock/include/nsock.h nsock/include/nsock_config.h \
  NmapOps.h nmap.h xml.h
nmap_ftp.o: nmap_ftp.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h nmap_ftp.h scan_lists.h \
  output.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h nsock/include/nsock.h nsock/include/nsock_config.h \
  NmapOps.h nmap_error.h tcpip.h libpcap/pcap.h libpcap/pcap/pcap.h \
  libpcap/pcap/bpf.h Target.h libnetutil/netutil.h \
  libdnet-stripped/include/dnet.h libdnet-stripped/include/dnet/os.h \
  libdnet-stripped/include/dnet/eth.h libdnet-stripped/include/dnet/ip.h \
  libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h portreasons.h portlist.h \
  scan_engine.h timing.h osscan.h osscan2.h nmap_tty.h
NmapOps.o: NmapOps.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h NmapOps.h scan_lists.h \
  output.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h nsock/include/nsock.h nsock/include/nsock_config.h \
  osscan.h nmap_error.h
NmapOutputTable.o: NmapOutputTable.cc NmapOutputTable.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h nmap_error.h nmap_config.h
nmap_tty.o: nmap_tty.cc nmap_config.h nmap.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h nmap_tty.h NmapOps.h \
  scan_lists.h output.h nse_main.h liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lualib.h nsock/include/nsock.h \
  nsock/include/nsock_config.h
osscan2.o: osscan2.cc osscan.h nbase/nbase.h nbase/nbase_config.h \
  nbase/nbase_ipv6.h osscan2.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libpcap/pcap.h \
  libpcap/pcap/pcap.h libpcap/pcap/bpf.h timing.h NmapOps.h nmap.h \
  nmap_config.h scan_lists.h output.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lualib.h \
  nsock/include/nsock.h nsock/include/nsock_config.h tcpip.h Target.h \
  libnetutil/netutil.h portreasons.h portlist.h scan_engine.h utils.h \
  nmap_error.h FPEngine.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/ARPHeader.h libnetutil/NetworkLayerElement.h \
  libnetutil/DataLinkLayerElement.h libnetutil/EthernetHeader.h \
  libnetutil/ICMPHeader.h libnetutil/ICMPv4Header.h \
  libnetutil/ICMPv6Header.h libnetutil/ICMPv6Option.h \
  libnetutil/ICMPv6RRBody.h libnetutil/IPv4Header.h \
  libnetutil/IPv6Header.h libnetutil/RawData.h libnetutil/TCPHeader.h \
  libnetutil/TransportLayerElement.h libnetutil/UDPHeader.h \
  libnetutil/HopByHopHeader.h libnetutil/IPv6ExtensionHeader.h \
  libnetutil/DestOptsHeader.h libnetutil/FragmentHeader.h \
  libnetutil/RoutingHeader.h libnetutil/PacketParser.h \
  FingerPrintResults.h struct_ip.h
osscan.o: osscan.cc osscan.h nbase/nbase.h nbase/nbase_config.h \
  nbase/nbase_ipv6.h NmapOps.h nmap.h nmap_config.h scan_lists.h \
  output.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h nsock/include/nsock.h nsock/include/nsock_config.h \
  charpool.h FingerPrintResults.h FPEngine.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/netutil.h libpcap/pcap.h libpcap/pcap/pcap.h \
  libpcap/pcap/bpf.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h nmap_error.h
output.o: output.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h output.h scan_lists.h \
  nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h nsock/include/nsock.h nsock/include/nsock_config.h \
  osscan.h osscan2.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libpcap/pcap.h \
  libpcap/pcap/pcap.h libpcap/pcap/bpf.h timing.h NmapOps.h \
  NmapOutputTable.h MACLookup.h portreasons.h protocols.h \
  FingerPrintResults.h FPEngine.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/netutil.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h tcpip.h Target.h portlist.h scan_engine.h \
  nmap_error.h utils.h xml.h
payload.o: payload.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h NmapOps.h scan_lists.h \
  output.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h nsock/include/nsock.h nsock/include/nsock_config.h \
  payload.h utils.h nmap_error.h
portlist.o: portlist.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h portlist.h nse_main.h \
  liblua/lua.h liblua/luaconf.h liblua/lauxlib.h liblua/lualib.h \
  scan_lists.h portreasons.h nmap_error.h NmapOps.h output.h \
  nsock/include/nsock.h nsock/include/nsock_config.h services.h \
  protocols.h tcpip.h libpcap/pcap.h libpcap/pcap/pcap.h \
  libpcap/pcap/bpf.h libnetutil/netutil.h \
  libdnet-stripped/include/dnet.h libdnet-stripped/include/dnet/os.h \
  libdnet-stripped/include/dnet/eth.h libdnet-stripped/include/dnet/ip.h \
  libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h
portreasons.o: portreasons.cc portlist.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lualib.h scan_lists.h \
  portreasons.h output.h nsock/include/nsock.h \
  nsock/include/nsock_config.h NmapOps.h nmap.h nmap_config.h Target.h \
  libnetutil/netutil.h libpcap/pcap.h libpcap/pcap/pcap.h \
  libpcap/pcap/bpf.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h scan_engine.h timing.h osscan.h \
  osscan2.h xml.h
protocols.o: protocols.cc protocols.h nbase/nbase.h nbase/nbase_config.h \
  nbase/nbase_ipv6.h NmapOps.h nmap.h nmap_config.h scan_lists.h \
  output.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h nsock/include/nsock.h nsock/include/nsock_config.h \
  services.h charpool.h nmap_error.h utils.h
scan_engine.o: scan_engine.cc portreasons.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h \
  libdnet-stripped/include/dnet.h libdnet-stripped/include/dnet/os.h \
  libdnet-stripped/include/dnet/eth.h libdnet-stripped/include/dnet/ip.h \
  libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h scan_engine.h scan_lists.h \
  timing.h libpcap/pcap.h libpcap/pcap/pcap.h libpcap/pcap/bpf.h \
  scan_engine_connect.h scan_engine_raw.h tcpip.h NmapOps.h nmap.h \
  nmap_config.h output.h nse_main.h liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lualib.h nsock/include/nsock.h \
  nsock/include/nsock_config.h nmap_tty.h payload.h Target.h \
  libnetutil/netutil.h portlist.h osscan.h osscan2.h targets.h \
  TargetGroup.h utils.h nmap_error.h struct_ip.h
scan_engine_connect.o: scan_engine_connect.cc nmap_error.h nmap_config.h \
  nbase/nbase.h nbase/nbase_config.h nbase/nbase_ipv6.h tcpip.h \
  libpcap/pcap.h libpcap/pcap/pcap.h libpcap/pcap/bpf.h Target.h \
  libnetutil/netutil.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lualib.h scan_lists.h \
  portreasons.h portlist.h scan_engine.h timing.h osscan.h osscan2.h \
  scan_engine_connect.h NmapOps.h nmap.h output.h nsock/include/nsock.h \
  nsock/include/nsock_config.h
scan_engine_raw.o: scan_engine_raw.cc nmap_error.h nmap_config.h \
  nbase/nbase.h nbase/nbase_config.h nbase/nbase_ipv6.h NmapOps.h nmap.h \
  scan_lists.h output.h nse_main.h liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lualib.h nsock/include/nsock.h \
  nsock/include/nsock_config.h Target.h libnetutil/netutil.h \
  libpcap/pcap.h libpcap/pcap/pcap.h libpcap/pcap/bpf.h \
  libdnet-stripped/include/dnet.h libdnet-stripped/include/dnet/os.h \
  libdnet-stripped/include/dnet/eth.h libdnet-stripped/include/dnet/ip.h \
  libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h portreasons.h portlist.h \
  scan_engine.h timing.h osscan.h osscan2.h payload.h scan_engine_raw.h \
  struct_ip.h tcpip.h utils.h
scan_lists.o: scan_lists.cc scan_lists.h nmap_error.h nmap_config.h \
  nbase/nbase.h nbase/nbase_config.h nbase/nbase_ipv6.h NmapOps.h nmap.h \
  output.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h nsock/include/nsock.h nsock/include/nsock_config.h \
  protocols.h services.h
service_scan.o: service_scan.cc service_scan.h portlist.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lualib.h scan_lists.h \
  portreasons.h timing.h NmapOps.h nmap.h nmap_config.h output.h \
  nsock/include/nsock.h nsock/include/nsock_config.h Target.h \
  libnetutil/netutil.h libpcap/pcap.h libpcap/pcap/pcap.h \
  libpcap/pcap/bpf.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h scan_engine.h osscan.h osscan2.h \
  utils.h nmap_error.h protocols.h nmap_tty.h
services.o: services.cc scan_lists.h services.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h NmapOps.h nmap.h nmap_config.h \
  output.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h nsock/include/nsock.h nsock/include/nsock_config.h \
  charpool.h nmap_error.h utils.h
Target.o: Target.cc Target.h nbase/nbase.h nbase/nbase_config.h \
  nbase/nbase_ipv6.h libnetutil/netutil.h libpcap/pcap.h \
  libpcap/pcap/pcap.h libpcap/pcap/bpf.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lualib.h scan_lists.h \
  portreasons.h portlist.h scan_engine.h timing.h osscan.h osscan2.h \
  FingerPrintResults.h FPEngine.h nsock/include/nsock.h \
  nsock/include/nsock_config.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/ARPHeader.h libnetutil/NetworkLayerElement.h \
  libnetutil/DataLinkLayerElement.h libnetutil/EthernetHeader.h \
  libnetutil/ICMPHeader.h libnetutil/ICMPv4Header.h \
  libnetutil/ICMPv6Header.h libnetutil/ICMPv6Option.h \
  libnetutil/ICMPv6RRBody.h libnetutil/IPv4Header.h \
  libnetutil/IPv6Header.h libnetutil/RawData.h libnetutil/TCPHeader.h \
  libnetutil/TransportLayerElement.h libnetutil/UDPHeader.h \
  libnetutil/HopByHopHeader.h libnetutil/IPv6ExtensionHeader.h \
  libnetutil/DestOptsHeader.h libnetutil/FragmentHeader.h \
  libnetutil/RoutingHeader.h libnetutil/PacketParser.h NmapOps.h nmap.h \
  nmap_config.h output.h nmap_error.h
NewTargets.o: NewTargets.cc NewTargets.h NmapOps.h nmap.h nmap_config.h \
  nbase/nbase.h nbase/nbase_config.h nbase/nbase_ipv6.h scan_lists.h \
  output.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h nsock/include/nsock.h nsock/include/nsock_config.h \
  nmap_error.h
TargetGroup.o: TargetGroup.cc tcpip.h nbase/nbase.h nbase/nbase_config.h \
  nbase/nbase_ipv6.h libpcap/pcap.h libpcap/pcap/pcap.h \
  libpcap/pcap/bpf.h TargetGroup.h NmapOps.h nmap.h nmap_config.h \
  scan_lists.h output.h nse_main.h liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lualib.h nsock/include/nsock.h \
  nsock/include/nsock_config.h nmap_error.h libnetutil/netutil.h \
  libdnet-stripped/include/dnet.h libdnet-stripped/include/dnet/os.h \
  libdnet-stripped/include/dnet/eth.h libdnet-stripped/include/dnet/ip.h \
  libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h
targets.o: targets.cc nbase/nbase_addrset.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h targets.h TargetGroup.h \
  timing.h tcpip.h libpcap/pcap.h libpcap/pcap/pcap.h libpcap/pcap/bpf.h \
  NmapOps.h nmap.h nmap_config.h scan_lists.h output.h nse_main.h \
  liblua/lua.h liblua/luaconf.h liblua/lauxlib.h liblua/lualib.h \
  nsock/include/nsock.h nsock/include/nsock_config.h NewTargets.h \
  Target.h libnetutil/netutil.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h portreasons.h portlist.h \
  scan_engine.h osscan.h osscan2.h nmap_dns.h utils.h nmap_error.h xml.h
tcpip.o: tcpip.cc nmap.h nmap_config.h nbase/nbase.h nbase/nbase_config.h \
  nbase/nbase_ipv6.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h tcpip.h libpcap/pcap.h \
  libpcap/pcap/pcap.h libpcap/pcap/bpf.h NmapOps.h scan_lists.h output.h \
  nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h nsock/include/nsock.h nsock/include/nsock_config.h \
  Target.h libnetutil/netutil.h portreasons.h portlist.h scan_engine.h \
  timing.h osscan.h osscan2.h utils.h nmap_error.h struct_ip.h
timing.o: timing.cc timing.h nbase/nbase.h nbase/nbase_config.h \
  nbase/nbase_ipv6.h NmapOps.h nmap.h nmap_config.h scan_lists.h \
  output.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h nsock/include/nsock.h nsock/include/nsock_config.h \
  utils.h nmap_error.h xml.h
traceroute.o: traceroute.cc nmap_dns.h nbase/nbase.h nbase/nbase_config.h \
  nbase/nbase_ipv6.h nmap_error.h nmap_config.h nmap_tty.h osscan2.h \
  libdnet-stripped/include/dnet.h libdnet-stripped/include/dnet/os.h \
  libdnet-stripped/include/dnet/eth.h libdnet-stripped/include/dnet/ip.h \
  libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libpcap/pcap.h \
  libpcap/pcap/pcap.h libpcap/pcap/bpf.h timing.h payload.h NmapOps.h \
  nmap.h scan_lists.h output.h nse_main.h liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lualib.h nsock/include/nsock.h \
  nsock/include/nsock_config.h Target.h libnetutil/netutil.h \
  portreasons.h portlist.h scan_engine.h osscan.h tcpip.h struct_ip.h
utils.o: utils.cc nmap.h nmap_config.h nbase/nbase.h nbase/nbase_config.h \
  nbase/nbase_ipv6.h utils.h nmap_error.h NmapOps.h scan_lists.h \
  output.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h nsock/include/nsock.h nsock/include/nsock_config.h
xml.o: xml.cc output.h scan_lists.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lualib.h \
  nsock/include/nsock.h nsock/include/nsock_config.h xml.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h
nse_main.o: nse_main.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h nmap_error.h portlist.h \
  nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h scan_lists.h portreasons.h nsock/include/nsock.h \
  nsock/include/nsock_config.h NmapOps.h output.h timing.h Target.h \
  libnetutil/netutil.h libpcap/pcap.h libpcap/pcap/pcap.h \
  libpcap/pcap/bpf.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h scan_engine.h osscan.h osscan2.h \
  nmap_tty.h xml.h nse_utility.h nse_fs.h nse_nsock.h nse_nmaplib.h \
  nse_pcrelib.h nse_openssl.h nse_debug.h nse_lpeg.h nse_libssh2.h
nse_utility.o: nse_utility.cc Target.h nbase/nbase.h nbase/nbase_config.h \
  nbase/nbase_ipv6.h libnetutil/netutil.h libpcap/pcap.h \
  libpcap/pcap/pcap.h libpcap/pcap/bpf.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lualib.h scan_lists.h \
  portreasons.h portlist.h scan_engine.h timing.h osscan.h osscan2.h \
  nse_utility.h nmap_config.h
nse_nsock.o: nse_nsock.cc nsock/include/nsock.h \
  nsock/include/nsock_config.h nmap_error.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h NmapOps.h nmap.h scan_lists.h \
  output.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h tcpip.h libpcap/pcap.h libpcap/pcap/pcap.h \
  libpcap/pcap/bpf.h protocols.h nse_nsock.h nse_utility.h \
  nse_ssl_cert.h
nse_dnet.o: nse_dnet.cc nsock/include/nsock.h \
  nsock/include/nsock_config.h nmap_error.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h NmapOps.h nmap.h scan_lists.h \
  output.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lualib.h tcpip.h libpcap/pcap.h libpcap/pcap/pcap.h \
  libpcap/pcap/bpf.h libnetutil/netutil.h \
  libdnet-stripped/include/dnet.h libdnet-stripped/include/dnet/os.h \
  libdnet-stripped/include/dnet/eth.h libdnet-stripped/include/dnet/ip.h \
  libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h nse_utility.h struct_ip.h
nse_fs.o: nse_fs.cc liblua/lauxlib.h liblua/lua.h liblua/luaconf.h nmap.h \
  nmap_config.h nbase/nbase.h nbase/nbase_config.h nbase/nbase_ipv6.h \
  nse_fs.h nse_utility.h nmap_error.h NmapOps.h scan_lists.h output.h \
  nse_main.h liblua/lualib.h nsock/include/nsock.h \
  nsock/include/nsock_config.h
nse_nmaplib.o: nse_nmaplib.cc liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lualib.h nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/nbase_ipv6.h nmap_error.h NmapOps.h \
  scan_lists.h output.h nse_main.h nsock/include/nsock.h \
  nsock/include/nsock_config.h FingerPrintResults.h FPEngine.h \
  libnetutil/npacket.h libnetutil/ApplicationLayerElement.h \
  libnetutil/PacketElement.h libnetutil/netutil.h libpcap/pcap.h \
  libpcap/pcap/pcap.h libpcap/pcap/bpf.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h \
  libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h osscan.h Target.h portreasons.h portlist.h \
  scan_engine.h timing.h osscan2.h NewTargets.h tcpip.h service_scan.h \
  nmap_dns.h protocols.h nse_nmaplib.h nse_utility.h nse_nsock.h \
  nse_dnet.h
nse_debug.o: nse_debug.cc liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  nse_debug.h output.h scan_lists.h nse_main.h liblua/lualib.h \
  nsock/include/nsock.h nsock/include/nsock_config.h
nse_pcrelib.o: nse_pcrelib.cc liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h nbase/nbase.h nbase/nbase_config.h nbase/nbase_ipv6.h \
  nmap_error.h nmap_config.h nse_pcrelib.h
nse_lpeg.o: nse_lpeg.cc liblua/lauxlib.h liblua/lua.h liblua/luaconf.h \
  lpeg.c
